# Generated by Django 3.0.2 on 2020-02-09 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewDogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deliveryLocation', models.CharField(max_length=200)),
                ('customer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(blank=True, to='viewDogs.Dogs')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(blank=True, to='viewDogs.Dogs')),
            ],
        ),
    ]
