# Generated by Django 3.0.2 on 2020-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stockNo', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/images/')),
                ('breed', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
